### ISSUE TITLE
Race condition in ignition-disks.service / systemd-fsck-root.service

### ISSUE THREAD

**Issue by laenion** [coreos/ignition-dracut#114]
### Problem
We are occasionally seeing a race condition with Ignition, where systemd will not continue booting after executing _ignition-disks.service_. This is happening when using a `partitions` section in the Ignition config.

### Analysis
Ignition will call `sgdisk` to get partition information, which will cause a de- and re-registration of the attached devices, and finally ends in the following systemd state:
```
Sep 30 11:41:02 linux-i34r ignition[464]: disks: createPartitions: op(2): running sgdisk with options: [--pretend --delete=3 --new=3:30771200:+32143327 /run/ignition/dev_aliases/dev/sda]
Sep 30 11:41:02 linux-i34r kernel:  sda: sda1 sda2 sda3
Sep 30 11:41:02 linux-i34r systemd[1]: dev-disk-by\x2did-scsi\x2d1ATA_VBOX_HARDDISK_VB153906d6\x2d80cd8193\x2dpart2.device: Changed plugged -> dead
Sep 30 11:41:02 linux-i34r systemd[1]: dev-disk-by\x2dpartuuid-b475923b\x2dd1d4\x2d416e\x2d87e7\x2d92bbd3559c34.device: Changed plugged -> dead
Sep 30 11:41:02 linux-i34r systemd[1]: dev-disk-by\x2dpath-pci\x2d0000:00:0d.0\x2data\x2d1\x2dpart2.device: Changed plugged -> dead
Sep 30 11:41:02 linux-i34r systemd[1]: dev-disk-by\x2did-scsi\x2dSATA_VBOX_HARDDISK_VB153906d6\x2d80cd8193\x2dpart2.device: Changed plugged -> dead
Sep 30 11:41:02 linux-i34r systemd[1]: dev-disk-by\x2duuid-154fb785\x2d8150\x2d4fb9\x2db212\x2d80f27032a64f.device: Changed plugged -> dead
Sep 30 11:41:02 linux-i34r systemd[1]: systemd-fsck-root.service: Trying to enqueue job systemd-fsck-root.service/stop/replace
Sep 30 11:41:02 linux-i34r systemd[1]: Added job systemd-fsck-root.service/stop to transaction.
Sep 30 11:41:02 linux-i34r systemd[1]: Pulling in sysroot.mount/stop from systemd-fsck-root.service/stop
Sep 30 11:41:02 linux-i34r systemd[1]: Added job sysroot.mount/stop to transaction.
Sep 30 11:41:02 linux-i34r systemd[1]: Pulling in initrd-root-fs.target/stop from sysroot.mount/stop
Sep 30 11:41:02 linux-i34r systemd[1]: Added job initrd-root-fs.target/stop to transaction.
Sep 30 11:41:02 linux-i34r systemd[1]: Pulling in ignition-mount.service/stop from initrd-root-fs.target/stop
Sep 30 11:41:02 linux-i34r systemd[1]: Added job ignition-mount.service/stop to transaction.
Sep 30 11:41:02 linux-i34r systemd[1]: Pulling in ignition-files.service/stop from ignition-mount.service/stop
Sep 30 11:41:02 linux-i34r systemd[1]: Added job ignition-files.service/stop to transaction.
Sep 30 11:41:02 linux-i34r systemd[1]: Pulling in ignition-complete.target/stop from ignition-files.service/stop
Sep 30 11:41:02 linux-i34r systemd[1]: Added job ignition-complete.target/stop to transaction.
Sep 30 11:41:02 linux-i34r systemd[1]: Pulling in initrd.target/stop from ignition-complete.target/stop
Sep 30 11:41:02 linux-i34r systemd[1]: Added job initrd.target/stop to transaction
```
See the [complete log file](https://github.com/coreos/ignition-dracut/files/3672001/ignition-broken.log) for more details.

### How to reproduce
While this is a timing issue which may occur only very rarely on most systems, there are some "optimized" setups which will trigger this behavior quite often. In our case we can reliably reproduce this with openSUSE MicroOS on virtual machines with only **one CPU**. Example: when using VirtualBox about 9 out of 10 boots will be stuck. We have also seen this on KVM when using only one CPU.

A corresponding configuration could be
```
{
	"ignition": { "version": "3.0.0" },
	"storage": {
		"disks": [
			{
				"device": "/dev/sda",
				"wipeTable": false,
				"partitions": [
					{
						"number": 3,
						"wipePartitionEntry": false
					}
				]
			}
		]
	}
}
```

### Possible solution
One possible solution could be to add `Before=systemd-fsck-root.service` to _ignition-disks.service_. I currently can't see any disadvantage of this approach, but I wanted to discuss this here before opening a pull request.

Judging from https://github.com/coreos/ignition/blob/master/internal/exec/stages/disks/disks.go#L90-L116 there seem to be more similar cases.

**Comment by ajeddeloh** [comment]
Thanks for the bug report with great logs!

Looking at the dependencies and ordering constraints on that unit:
 ```
# systemd-fsck-root.service from FCOS
BindsTo=dev-disk-by\x2dlabel-root.device
Conflicts=shutdown.target
After=initrd-root-device.target local-fs-pre.target dev-disk-by\x2dlabel-root.device
Before=shutdown.target
```
It's `After=initrd-root-device.target`. I think it probably makes sense to order the disks stage `Before=initrd-root-device.target` which should fix this as well as any other similar problems. @jlebon thoughts?

**Comment by jlebon** [comment]
> Looking at the dependencies and ordering constraints on that unit:
> ```
> # systemd-fsck-root.service from FCOS
> ...
> ```

Hmm, that's weird, I see:

```
[Unit]
Description=File System Check on Root Device
Documentation=man:systemd-fsck-root.service(8)
DefaultDependencies=no
Conflicts=shutdown.target
Before=local-fs.target shutdown.target
ConditionPathIsReadWrite=!/
```

Ahh OK, I see. The real root has a dedicated fsck unit for root, but in the initrd, only the `systemd-fsck@.service` template exists, and that one gets instantiated for the root filesystem.

> I think it probably makes sense to order the disks stage `Before=initrd-root-device.target`

Yeah, I think that makes sense. I was debating whether we wanted to go to the extreme and do `Before=local-fs-pre.target` like CL. I think the confusion here is that `systemd.special` says:

       local-fs-pre.target
           This target unit is automatically ordered before all local mount points marked
           with auto (see above). It can be used to execute certain units before all local
           mounts.

but that doesn't apply to the initrd, since root is mounted later on after `local-fs.target`. So unless we have a reason to run this early, I'd agree just bumping it back to `initrd-root-device.target` only.

**Comment by ajeddeloh** [comment]
> Ahh OK, I see. The real root has a dedicated fsck unit for root, but in the initrd, only the systemd-fsck@.service template exists, and that one gets instantiated for the root filesystem.

Not quite, a dedicated not-instantiated unit is generated from a generator; that's what my excerpt is from.

> since root is mounted later on after local-fs.target

The root is mounted after `initrd-root-device.target` and before `local-fs.target` (as well as `initrd-root-fs.target`).

> I'd agree just bumping it back to initrd-root-device.target only.

SGTM

**Comment by jlebon** [comment]
> The root is mounted after initrd-root-device.target and before local-fs.target (as well as initrd-root-fs.target).

Most of our services run after `basic.target`, which is after `local-fs.target` (see `bootup(7)`).

**Comment by ajeddeloh** [comment]
Oh right, sorry, mixed up `local-fs.target` and `initrd-fs.target`
