### ISSUE TITLE
[spec2x] coreos-teardown-initramfs-network: evaluate necessity of the script

### ISSUE THREAD

**Issue by yuqi-zhang** [coreos/ignition-dracut#119]
Currently on the spec2x branch of ignition, we have a simple script that tears down the network interfaces in the initramfs, right before we switch to the real root: https://github.com/coreos/ignition-dracut/blob/spec2x/dracut/30ignition/coreos-teardown-initramfs-network.sh

The original point of the script was that we wanted users to set up their networking (e.g. a static IP address) via ignition on RHCOS. NetworkManager inherited initamfs networking, so if the user did a dhcp to fetch ignition configs in the initramfs, the static networking would not be set up until a reboot. Note that we only brought down network interfaces and didn't really care about bonding, etc. since we didn't expect users to set that up in the initramfs.

Now the coreos-installer has the ability to persist kargs, so users are able to set up their networking that way. I think with that in place, and the fact that we're moving to NM managed initramfs networking, we should re-evaluate how we're using handling networking in the initramfs.

Also note that FCOS already uses NM dracut networking, and thus does not use `ifcfg` files as their source of truth, but instead NM keyfiles.

**Comment by jlebon** [comment]
> Also note that FCOS already uses NM dracut networking

This is not yet the case. See https://github.com/coreos/fedora-coreos-config/pull/259.

**Comment by yuqi-zhang** [comment]
Ah, my bad, thanks for the clarification. Is it correct to say "FCOS uses NetworkManager keyfiles, but do not yet use NM for dracut networking" then?

**Comment by dustymabe** [comment]
considering https://github.com/coreos/fedora-coreos-tracker/issues/394#issuecomment-599721763 and that we just merged similar functionality into the master branch (#159) I think we have deemed functionality like this necessary.
