### ISSUE TITLE
Creating users does not mount /home

### ISSUE THREAD

**Issue by thkukuk** [coreos/ignition-dracut#23]
Ignition can create new users in initrd, but if /home is an extra partition, it will not be mounted on /sysroot before. So the home directory of new users are shadowed by the mount of /home later.

**Comment by ajeddeloh** [comment]
Yeah, this is the same as #18. For RHCOS and FCOS (which this supports) `/home` is not separated by default. For your use case, you can add an entry in the `storage.filesystems` section in the base config that specifies the mount path and have the initramfs mount it for you.

**Comment by darkmuggle** [comment]
Closing this as stale.
