### ISSUE TITLE
Documentation for coreos about first_boot and parameter used in RH CoreOs image do not match

### ISSUE THREAD

**Issue by yrobla** [coreos/ignition-dracut#29]
In CoreOS documentation, the kernel parameter used to boot ignition is called first_boot. But in latest RH CoreOS images, the parameter had been renamed and called firstboot.
So far this is confusing when using this documentation as the source of truth because the parameter is not matching, so the ignition first boot is not being applied.

**Comment by cgwalters** [comment]
Yeah, we should change the code here to honor both parameters.

**Comment by bgilbert** [comment]
Is it still early enough that we can drop the `firstboot` spelling before it ends up in documentation and such?

**Comment by ashcrow** [comment]
@bgilbert as in revert back to `first_boot`?

**Comment by jlebon** [comment]
With #24 (i.e. https://github.com/coreos/ignition/issues/646), there's also talks of dropping the `coreos` naming in favour of `ignition`. So that'd leave us with two legacy aliases. Given that it's still relatively early, might be cleaner to just drop `coreos.firstboot` and only support `coreos.first_boot` for now until we also add `ignition.first_boot` support.

**Comment by dustymabe** [comment]
> Given that it's still relatively early, might be cleaner to just drop `coreos.firstboot` and only support `coreos.first_boot` for now until we also add `ignition.first_boot` support.

:+1:

**Comment by LorbusChris** [comment]
Do we want to rename `$coreos_firstboot` in https://github.com/coreos/fedora-coreos-config/blob/master/image.ks#L36 as well? Maybe to something like `$ignition_first_boot_karg`? Or leave that part as is?

**Comment by ajeddeloh** [comment]
> It is possible we don't need that last one since not many people have been using FCOS, but it seems harmless.

I'd say axe it. No need to carry it and less legacy = better. In fact, lets axe the second one too, not need to carry both in either OS. CL can continue using `coreos.first_boot` and *cos can use `ignition.firstboot`.

We could also add compile-time switches in Ignition for things like `coreos.config.url`/`ignition.config.url`.

**Comment by dustymabe** [comment]
> > 
> 
> I'd say axe it. No need to carry it and less legacy = better. In fact, lets axe the second one too, not need to carry both in either OS. CL can continue using `coreos.first_boot` and *cos can use `ignition.firstboot`.

I think we explicitly want to keep undocumented support for `coreos.first_boot` because people coming from CL would be more comfortable and also we don't quite have docs yet, so people looking at old CL docs might make a mistake. Some of the people working on openshift/RHCOS had this problem so backwards compat there was the goal.

**Comment by ajeddeloh** [comment]
But we _will_ have docs by the time we release. I don't want to carry legacy things forward that we don't need to when we have the best chance to break compat.

**Comment by bgilbert** [comment]
+1 to dropping all compat aliases.  We can re-add `coreos.first_boot` if its absence turns out to confuse people.

**Comment by dustymabe** [comment]
ok. @yrobla FYI through this discussion we have elected to not add the legacy boot option back.

@yrobla - we are going to be making a change soon around this and would like to coordinate with you when we do it so that we don't break any existing workflows. What's the best way to contact you?

**Comment by dustymabe** [comment]
@LorbusChris - this means we only need to support `ignition.firstboot` on the kernel command line.

**Comment by LorbusChris** [comment]
Do we want to retain support for `coreos.config.*` or drop that as well?

Where is the `/boot/coreos-firstboot` file created in the first place? Do we want to rename that to `/boot/ignition-firstboot`, too?

**Comment by dustymabe** [comment]
Yes let's change it. For now it's done here:

https://github.com/coreos/coreos-assembler/blob/c12934aa1e4551166565064a9a2d98d4bfe2d977/src/virt-install#L76-L83

I'd really like a better answer for how we detect first boot in the future but for now that's how it's done.

**Comment by ajeddeloh** [comment]
> Do we want to retain support for coreos.config.* or drop that as well?

The functionality? Absolutely. The name? Probably not. `ignition.config.url` is probably a better name.

**Comment by dustymabe** [comment]
closing this one out. As mentioned in https://github.com/coreos/ignition-dracut/issues/29#issuecomment-438896299 we chose to move forward with `ignition.firstboot` and we'll be adding docs for this.
