### ISSUE TITLE
Rename coreos.oem.id kernel command-line argument

### ISSUE THREAD

**Issue by bgilbert** [coreos/ignition-dracut#31]
Rename `coreos.oem.id` to something preferably containing neither `coreos` nor `oem`.

xref: https://github.com/coreos/ignition/issues/684

**Comment by lucab** [comment]
Just a quick comment to note that this argument is not specific to Ignition (and coreos-metadata), but can be also consumed by service units via `ConditionKernelCommandLine=`. Perhaps we should have FCOS-defined registry with known values?

**Comment by dustymabe** [comment]
> xref: [coreos/ignition#684](https://github.com/coreos/ignition/issues/684)

so we'd need to wait for the discussion in 684 to finish before doing something here?
