### ISSUE TITLE
Support base and user configs

### ISSUE THREAD

**Issue by bgilbert** [coreos/ignition-dracut#32]
We will need to support:

- Platform-specific base configs.  (Also, default configs, if https://github.com/coreos/ignition/issues/668 is not implemented.)  Unlike in CL, these should probably all be kept in the initramfs image.
- User-supplied `config.ign`, perhaps in the `/boot` partition.

In CL these are handled by `ignition-setup.service`, which is currently disabled here because the original version relies on the OEM partition.

**Comment by yrobla** [comment]
I think that being able to ship user-supplied config.ign is something needed. For the baremetal use case is specially useful, as there are no other ways to parameterize. In case of PXE boot, people could add kernel parameters with the coreos.config_url and it will work. But in case of using virtual media, modifying kernel parameters is not an option, so having the ability to embed some config.ign in the image for modifications like inject ssh key, start some services, etc... is very useful.

**Comment by yrobla** [comment]
Sure, happy to work on that!
