### ISSUE TITLE
Improve reporting of Ignition failures

### ISSUE THREAD

**Issue by bgilbert** [coreos/ignition-dracut#35]
After Ignition fails, we should:

- Explain to the user that it has failed, and why
- Offer to drop to an initramfs emergency shell
- If the user doesn't respond within 5 minutes, reboot the system (to try again)

It appears that, instead, we currently rerun Ignition indefinitely.

In CL this is handled by the [99emergency-timeout](https://github.com/coreos/bootengine/tree/master/dracut/99emergency-timeout) dracut module.

**Comment by rfairley** [comment]
Thinking of taking a look into this - I think for now we can bring `99emergency-timeout` forward straight into `ignition-dracut` (making sure it works in FCOS, and RHCOS too if we backport it). Future adjustments could be made to the module here if needed.
