### ISSUE TITLE
Remount of /sysroot read-write

### ISSUE THREAD

**Issue by thkukuk** [coreos/ignition-dracut#37]
Commit "3ec0b39106a0724982da64dc348a38da7a471467" (remove ignition-remount-sysroot.service files) breaks ignition at least on openSUSE, as the default is still to mount the root filesystem read-only.
I'm pretty sure that most distributions still mount root in read-only mode by default.

Can we re-add at least the ignition-remount-sysroot.service file? I don't think the var variant is really needed.

**Comment by dustymabe** [comment]
Thanks @thkukuk  for bringing this to our attention. Since @jlebon authored 3ec0b39106a0724982da64dc348a38da7a471467 I'll lean on him for expertise here. Maybe we can add the unit back and a ConditionKernelCommandLine to the unit.

**Comment by jlebon** [comment]
The backstory here is that today if you want systemd units with `ConditionFirstBoot=true` to fire on first boot, one has no choice but to mount `/sysroot` as rw. See e.g. https://github.com/systemd/systemd/issues/8268#issuecomment-410239359.

That said, if for whatever reason you really do want to keep mounting ro and don't care about supporting `ConditionFirstBoot`, there's no harm in reviving `ignition-remount-sysroot.service`.

**Comment by thkukuk** [comment]
On Mon, Jan 07, Jonathan Lebon wrote:

> The backstory here is that today if you want systemd units with
> ConditionFirstBoot=true to fire on first boot, one has no choice but to mount /
> sysroot as rw. See e.g. systemd/systemd#8268 (comment).

Ok, we solved that problem in different ways, depending on how you
install, with our installer (in that case, /etc/machine-id will be
generated already during installation and ConditionFirstBoot=true will
never happen), if you create golden images (for bare metal or virtualisation)
or if you use a read-only root filesystem.

> That said, if for whatever reason you really do want to keep mounting ro and
> don't care about supporting ConditionFirstBoot, there's no harm in reviving
> ignition-remount-sysroot.service.

As written, we solved that in different ways and currently don't plan
to change the default.

-- 
Thorsten Kukuk, Distinguished Engineer, Senior Architect SLES & MicroOS
SUSE LINUX GmbH, Maxfeldstr. 5, 90409 Nuernberg, Germany
GF: Felix Imendoerffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nuernberg)

**Comment by dustymabe** [comment]
@thkukuk - any chance you'd like to take a crack at adding `ignition-remount-sysroot.service` back?

**Comment by thkukuk** [comment]
I have a patch, I can create a pull requests the next days

-- 
Thorsten Kukuk, Distinguished Engineer, Senior Architect SLES & MicroOS
SUSE LINUX GmbH, Maxfeldstr. 5, 90409 Nuernberg, Germany
GF: Felix Imendoerffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nuernberg)

**Comment by dustymabe** [comment]
fixed by #38
