### ISSUE TITLE
ignition on fedora28

### ISSUE THREAD

**Issue by bcg62** [coreos/ignition-dracut#41]
Im trying to use ignition on fedora28, but it seems like ignition is running and trying to grab config.url=tftp://..... before my network is up, or the configured interface DHCP's

```
console=tty0 selinux=0 audit=0 nosoftlockup biosdevname=1 rd.neednet=1 ipv6.disable=1 nmi_watchdog=0 rootflags=noatime rd.shell rd.luks=0 rd.dm=0 rd.lvm=0 rd.writable.fsimg=1 rd.live.ram=1 crashkernel=auto log_buf_len=524288 LANG=en_US.UTF-8 root=live:ftp://.......tar.gz ignition.firstboot coreos.config.url=tftp://...... bootdev=management ifname=management:00:XX:XX:XX:XX:XX ip=management:dhcp
```

Is there something else i should be looking at? Is the systemd-networkd dracut module needed?

oddly when i run it without providing the config url, it runs after the network is setup.

**Comment by dustymabe** [comment]
are you using the ignition rpm from fedora or putting it together some other way? 

Here is the kernel command line we use for fedora coreos, but do note that we are using f29 and not f28: https://github.com/coreos/fedora-coreos-config/blob/a733e2cfb39cfc55981ad1d37c359665aece7dd3/image.ks#L32-L36

**Comment by bcg62** [comment]
Im using the rpms

```
dnf install -y dracut-network git-core gdisk ignition-dracut ignition
```

I just tried switching from `tftp://` to `http://` and the retry seems to mask the ordering issue. tftp has no retry functionality. 

do you notice some of the first few attempts failing?

**Comment by dustymabe** [comment]
i have noticed attempts failing in the past but the retry always took care of it so haven't had any issues.  I didn't realize tftp had no retry functionality.

**Comment by bcg62** [comment]
Just figured it out the hard way as well. Would be great if it did, Im already running tftp to support pxe booting this infrastructure and would like to avoid an additional http/nginx instance if possible

**Comment by bcg62** [comment]
output of it running before dhcp starts.

```Jan 28 18:07:20.977648 systemd[1]: Starting Ignition (disks)...
Jan 28 18:07:20.987408 ignition[603]: Ignition 0.29.1
Jan 28 18:07:20.987932 ignition[603]: reading system config file "/usr/lib/ignition/base.ign"
Jan 28 18:07:20.987980 ignition[603]: no config at "/usr/lib/ignition/base.ign"
Jan 28 18:07:20.988284 ignition[603]: parsed url from cmdline: "http://X.X.X.X/ftp/conf/cloud-init/ing"
Jan 28 18:07:20.988323 ignition[603]: GET http://X.X.X.X/ftp/conf/cloud-init/ing: attempt #1
Jan 28 18:07:20.988449 ignition[603]: GET error: Get http://X.X.X.X/ftp/conf/cloud-init/ing: dial tcp X.X.X.X:80: connect: network is unreachable
Jan 28 18:07:21.196268 ignition[603]: GET http://X.X.X.X/ftp/conf/cloud-init/ing: attempt #2
Jan 28 18:07:21.196327 ignition[603]: GET error: Get http://X.X.X.X/ftp/conf/cloud-init/ing: dial tcp X.X.X.X:80: connect: network is unreachable
Jan 28 18:07:21.596485 ignition[603]: GET http://X.X.X.X/ftp/conf/cloud-init/ing: attempt #3
Jan 28 18:07:21.596564 ignition[603]: GET error: Get http://X.X.X.X/ftp/conf/cloud-init/ing: dial tcp X.X.X.X:80: connect: network is unreachable
Jan 28 18:07:22.396704 ignition[603]: GET http://X.X.X.X/ftp/conf/cloud-init/ing: attempt #4
Jan 28 18:07:22.396901 ignition[603]: GET error: Get http://X.X.X.X/ftp/conf/cloud-init/ing: dial tcp X.X.X.X:80: connect: network is unreachable
Jan 28 18:07:23.997239 ignition[603]: GET http://X.X.X.X/ftp/conf/cloud-init/ing: attempt #5
Jan 28 18:07:23.997434 ignition[603]: GET error: Get http://X.X.X.X/ftp/conf/cloud-init/ing: dial tcp X.X.X.X:80: connect: network is unreachable
Jan 28 18:07:26.020973 dracut-initqueue[601]: Starting dhcp for interface management
Jan 28 18:07:26.049910 dracut-initqueue[601]: dhcp: PREINIT management up
Jan 28 18:07:26.070193 dhclient[858]: DHCPDISCOVER on management to 255.255.255.255 port 67 interval 8 (xid=0xfcc42651)
Jan 28 18:07:26.070736 dhclient[858]: DHCPREQUEST on management to 255.255.255.255 port 67 (xid=0xfcc42651)
Jan 28 18:07:26.070997 dhclient[858]: DHCPOFFER from X.X.X.X
Jan 28 18:07:26.071199 dhclient[858]: DHCPACK from X.X.X.X (xid=xxxxxxxxx)
Jan 28 18:07:26.092045 dracut-initqueue[601]: dhcp: BOND setting management
Jan 28 18:07:27.197485 ignition[603]: GET http://X.X.X.X/ftp/conf/cloud-init/ing: attempt #6
Jan 28 18:07:27.199128 ignition[603]: GET error: Get http://X.X.X.X/ftp/conf/cloud-init/ing: dial tcp X.X.X.X:80: connect: network is unreachable
Jan 28 18:07:32.197685 ignition[603]: GET http://X.X.X.X/ftp/conf/cloud-init/ing: attempt #7
Jan 28 18:07:32.253523 ignition[603]: GET result: OK
Jan 28 18:07:32.253690 ignition[603]: parsing config: {"ignition.......
Jan 28 18:07:32.259270 ignition[603]: disks: disks passed
Jan 28 18:07:32.259464 ignition[603]: Ignition finished successfully
Jan 28 18:07:32.261472 systemd[1]: Started Ignition (disks).
Jan 28 18:08:08.265720 systemd[1]: Starting Ignition (files)...```

**Comment by bgilbert** [comment]
You're right that Ignition should be retrying failed TFTP fetches.

The retry doesn't mask the ordering issue, it's the intentional solution to the ordering issue.  With networkd in Container Linux, where Ignition originated, there's not actually a good way to know when the network is up.  NetworkManager provides an API for that purpose, which we could use, but that's not currently the design.

**Comment by bcg62** [comment]
@bgilbert thanks, makes sense to me.  I probably wouldn't have noticed the failure had the retry functionality been in place.

**Comment by bgilbert** [comment]
Filed https://github.com/coreos/ignition/issues/712 for waiting to fetch until NetworkManager is ready.

This isn't an ignition-dracut bug, so I'll close this in favor of https://github.com/coreos/ignition/issues/711.  Thanks for reporting!
