### ISSUE TITLE
Support live PXE

### ISSUE THREAD

**Issue by bgilbert** [coreos/ignition-dracut#44]
Some changes will be needed to support PXE-to-live machines, which boot without a system disk.  These include:
- [x] Extend #43 to not mount `/boot` in the PXE case
- [x] The unit that removes the firstboot flag shouldn't try to mount `/boot` in the PXE case
- [x] Support something like CL's [custom PXE OEM](https://coreos.com/os/docs/latest/booting-with-pxe.html#adding-a-custom-oem) mechanism.  In CL this is done via lookaside code in Ignition, but that's being removed in https://github.com/coreos/ignition/pull/734 and doesn't really belong in Ignition anyway.  Instead ignition-setup can copy `config.ign` from some defined path in the initramfs, if it exists.  We should probably retain that indirection for flexibility, i.e. users should not create initramfs images containing `/usr/lib/ignition/user.ign`.

**Comment by dustymabe** [comment]
@bgilbert can this be closed? I do believe we have Live PXE support now in FCOS.
