### ISSUE TITLE
Not failing the boot if Ignition fails

### ISSUE THREAD

**Issue by jlebon** [coreos/ignition-dracut#59]
Right now, failures in e.g. `ignition-files` isn't failing the boot. We must have regressed on this at some point, because I clearly remember it being the case earlier. This is on FCOS, and el8 at least, which are both still on the `spec2x` branch.  Still investigating...

**Comment by ajeddeloh** [comment]
Do we need to / should we pull in https://github.com/coreos/bootengine/tree/master/dracut/99emergency-timeout ?

**Comment by bgilbert** [comment]
@ajeddeloh See #35.  `99emergency-timeout` is purely a UX improvement and separate from this issue.

**Comment by jlebon** [comment]
So, this is fixed now for the master branch, but not the `spec2x` branch. I updated #60 for that now.
