### ISSUE TITLE
Selinux is not working?

### ISSUE THREAD

**Issue by purpleidea** [coreos/ignition-dracut#62]
In the docs it says:

`enforcing=0`

Is selinux not supported or recommended for some reason? I'm not smart enough to figure out how to do battle against selinux and win, so if any experts could explain that would be appreciated! Many thanks!

**Comment by dustymabe** [comment]
where does it say that? we probably need to overhaul the docs and make a proper readme for this repo anyway

**Comment by jlebon** [comment]
See some more up to date docs in #63.

**Comment by purpleidea** [comment]
@dustymabe https://github.com/coreos/ignition-dracut/blob/b11553f9e2b530fbbb5a2504bc72b364829c879c/dracut/README.txt#L7

But @jlebon please don't delete the user guide for installing on fedora "classic".
