### ISSUE TITLE
Support PXE installs

### ISSUE THREAD

**Issue by jlebon** [coreos/ignition-dracut#68]
Right now, PXE installs on RHCOS are failing because `ignition-setup.service` tries to pull in `/boot`, which doesn't exist. See related commit: https://github.com/coreos/ignition-dracut/commit/77ba5bf5e923104375a8e6a6e55c6fecb0adf39f.

Seems like the logic we want for `ignition-setup.service` here is: "if there is a boot device, then wait for it, otherwise, skip me" ? Would be nicer if we'd just let systemd figure out the appropriate time out to wait for the device here rather than do this ourselves.

I guess doing `s/Requires=/Wants=/` might do the trick, though not sure if there's a more idiomatic way to do this.

**Comment by jlebon** [comment]
Actually, does the installer need Ignition at all? Can't we just conditionalize all our units on `ConditionKernelCommandLine=!coreos.inst=yes`?

**Comment by bgilbert** [comment]
Conditioning on `coreos.inst` would work for the installer but won't help live PXE, which will also have this problem.  And we can't skip the entire `ignition-setup.service` in the PXE case: we'll still need the platform-specific base config logic, since PXE boot is also possible e.g. on VMware.

**Comment by jlebon** [comment]
OK, I opened https://github.com/coreos/ignition-dracut/pull/69 against `spec2x` so @yuqi-zhang can at least test it out.

> Conditioning on `coreos.inst` would work for the installer but won't help live PXE, which will also have this problem.

Right, that makes sense. How are we planning to detect live PXE? If it's through a kernel arg, then we should be able to also conditionalize `ignition-setup.service` on that too, right?

**Comment by yuqi-zhang** [comment]
Upon closer check the error I ran into was POST rebooting, so I initially reported and erroneous error, sorry about that. The install to disk appears to have completed correctly, and then after reboot, I hit the error.

Post reboot kernel command line:
```
Using kernel command line parameters: BOOT_IMAGE=/ostree/rhcos-2a4caaede42239b71dc3082fa31a4cfd7965fb97a71e5424cfde3bf2e1e6f7c8/vmlinuz-4.18.0-80.el8.x86_64 rootflags=defaults,prjquota rw ignition.firstboot rd.neednet=1 ip=dhcp console=ttyS0,115200n8 root=UUID=1c184aa0-f4bf-433c-9589-72488c8c86ce ostree=/ostree/boot.0/rhcos/2a4caaede42239b71dc3082fa31a4cfd7965fb97a71e5424cfde3bf2e1e6f7c8/0
```
```
# lsblk
NAME MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sda    8:0    0  10G  0 disk
```

**Comment by jlebon** [comment]
OK, finally got a PXE install of RHCOS working!

```
$ lsblk
NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
sda      8:0    0  10G  0 disk
├─sda1   8:1    0   1M  0 part
├─sda2   8:2    0   1G  0 part /boot
└─sda3   8:3    0   9G  0 part /sysroot
```

@yuqi-zhang can you share your pxeconfig?

**Comment by yuqi-zhang** [comment]
```
DEFAULT pxeboot
TIMEOUT 20
PROMPT 0
LABEL pxeboot
    KERNEL r8-kernel
    APPEND ip=dhcp rd.neednet=1 initrd=r8-initramfs.img console=tty0 console=ttyS0 coreos.inst=yes coreos.inst.install_dev=sda coreos.inst.image_url=http://192.168.122.1:8000/r8-bios.raw.gz coreos.inst.ignition_url=http://192.168.122.1:8000/ignition.json
IPAPPEND 2
```

**Comment by jlebon** [comment]
Confirmed with @yuqi-zhang that it's working for him as well now.

**Comment by zshi-redhat** [comment]
> ```
> DEFAULT pxeboot
> TIMEOUT 20
> PROMPT 0
> LABEL pxeboot
>     KERNEL r8-kernel
>     APPEND ip=dhcp rd.neednet=1 initrd=r8-initramfs.img console=tty0 console=ttyS0 coreos.inst=yes coreos.inst.install_dev=sda coreos.inst.image_url=http://192.168.122.1:8000/r8-bios.raw.gz coreos.inst.ignition_url=http://192.168.122.1:8000/ignition.json
> IPAPPEND 2
> ```

@jlebon @yuqi-zhang I'm trying to do the same, pxe booting rhcos with libvirt VMs, I got one issue of not be able to find ``boot`` partition:
```
[   91.730207] systemd[1]: dev-disk-by\x2dlabel-boot.device: Job dev-disk-by\x2dlabel-boot.device/start timed out.
[   91.732920] systemd[1]: Timed out waiting for device dev-disk-by\x2dlabel-boot.device.
[   91.736221] systemd[1]: Dependency failed for Ignition (setup).
[   91.739338] systemd[1]: Dependency failed for Ignition Complete.
[   91.742479] systemd[1]: Dependency failed for Initrd Default Target.
[   91.745810] systemd[1]: initrd.target: Job initrd.target/start failed with result 'dependency'.
```

Do you know what might be the cause?

Here is the pxelinux.cfg I used for the bootstrap node:
```
DEFAULT pxeboot
TIMEOUT 20
PROMPT 0
LABEL pxeboot
    KERNEL rhcos/images/latest/installer-kernel
    APPEND ip=dhcp rd.neednet=1 initrd=rhcos/images/latest/installer-initramfs.img console=tty0 console=ttyS0 coreos.inst=yes coreos.inst.install_dev=sda coreos.inst.image_url=http://10.19.111.16:8000/rhcos/images/latest/metal-bios.raw coreos.inst.ignition_url=http://10.19.111.16:8000/rhcos/ignitions/bootstrap.ign
IPAPPEND 2
```
the metal-bios.raw is downloaded via ``https://releases-redhat-coreos.cloud.paas.upshift.redhat.com/storage/releases/ootpa/410.8.20190412.2/rhcos-410.8.20190412.2-metal-bios.raw``, it doesn't have gz suffix, but it's already in compressed format.

**Comment by zshi-redhat** [comment]
If I change the metal-bios.raw name to metal-bios.raw.gz, then the pxe booting stopped at :
```
[ OK ] Started Open-iSCSI. Starting dracut initqueue hook... 
[ OK ] Started Create Volatile Files and Directories. 
[ OK ] Reached target System Initialization. 
[ OK ] Reached target Basic System. 
[ OK ] Started dracut initqueue hook. 
[ OK ] Reached target Remote File Systems (Pre). 
[ OK ] Reached target CoreOS Installer Target. 
[ OK ] Started CoreOS Installer.
```
and never returned, is there a way to check the error message in such case?

**Comment by jlebon** [comment]
@zshi-redhat IIRC @yuqi-zhang hit the same issue and it was due to not having all the pxelinux files available. How are you setting up your PXE server? I personally do `dnf install -y syslinux-tftpboot` then grab all the files from `/tftpboot` (or you can `rpm2cpio`).

**Comment by zshi-redhat** [comment]
> @zshi-redhat IIRC @yuqi-zhang hit the same issue and it was due to not having all the pxelinux files available. How are you setting up your PXE server? I personally do `dnf install -y syslinux-tftpboot` then grab all the files from `/tftpboot` (or you can `rpm2cpio`).

Thanks for the reply!
I did the same by installing syslinux-tftpboot package, copying pxelinux.0 and ldlinux.c32 to the tftpboot folder, it failed with the same error.

**Comment by zshi-redhat** [comment]
> > @zshi-redhat IIRC @yuqi-zhang hit the same issue and it was due to not having all the pxelinux files available. How are you setting up your PXE server? I personally do `dnf install -y syslinux-tftpboot` then grab all the files from `/tftpboot` (or you can `rpm2cpio`).
> 
> Thanks for the reply!
> I did the same by installing syslinux-tftpboot package, copying pxelinux.0 and ldlinux.c32 to the tftpboot folder, it failed with the same error. Anything else I should try or any other configuration need to check?

The virt-install cmd I used for installing VMs is:
```
	virt-install \
		--name ${NODE_NAMES[$index]} \
		--memory 2048 \
		--vcpus 4 \
		--disk size=8,bus=scsi,pool=default \
		--controller type=scsi,model=virtio-scsi \
		--network default \
		--mac=${MACS[$index]} \
		--pxe \
		--os-variant generic
```

**Comment by yuqi-zhang** [comment]
That virt-install command looks fine, I tried with it and it installed/booted correctly for me.

For reference, I have a `pxelinux.cfg/default` file that looks like:
```
DEFAULT pxeboot
TIMEOUT 20
PROMPT 0
LABEL pxeboot
    KERNEL r8-kernel
    APPEND ip=dhcp rd.neednet=1 initrd=r8-initramfs.img console=tty0 console=ttyS0 coreos.inst=yes coreos.inst.install_dev=sda coreos.inst.image_url=http://192.168.122.1:8000/r8-bios.raw.gz coreos.inst.ignition_url=http://192.168.122.1:8000/ignition.json
IPAPPEND 2
```

and a `ignition.json` that looks like:
```
{"ignition":{"config":{},"security":{"tls":{}},"timeouts":{},"version":"2.2.0"},"networkd":{},"passwd":{"users":[{"groups":["sudo"],"name":"core","sshAuthorizedKeys":["ssh-rsa MY-KEY..."]}]}}
```

**Comment by yuqi-zhang** [comment]
Hmm, do you have DHCP set up for your libvirt network?

**Comment by zshi-redhat** [comment]
> Hmm, do you have DHCP set up for your libvirt network?

Yes, the dhcp config in default libvirt network looks like below:
```
  <ip address='192.168.122.1' netmask='255.255.255.0'>
    <tftp root='/var/lib/tftpboot'/>
    <dhcp>
      <range start='192.168.122.2' end='192.168.122.254'/>
      <host mac='52:54:00:zz:yy:xx' name='bootstrap' ip='192.168.122.20'/>
      <host mac='52:54:00:zz:yy:xx' name='master-1' ip='192.168.122.21'/>
      <host mac='52:54:00:zz:yy:xx' name='master-2' ip='192.168.122.22'/>
      <host mac='52:54:00:zz:yy:xx' name='master-3' ip='192.168.122.23'/>
      <host mac='52:54:00:zz:yy:xx' name='worker-1' ip='192.168.122.24'/>
      <bootp file='pxelinux.0'/>
    </dhcp>
```

**Comment by zshi-redhat** [comment]
I just use the auto-generated ignition file which looks similar to yours, but it also includes a storage section; for example, here is the ignition file for bootstrap node: http://pastebin.test.redhat.com/755224

**Comment by mrguitar** [comment]
I have a similar setup working w/ rhcos-410.8.20190415.2-metal-bios.raw and the only difference I can see is I'm using virtio instead of scsi devices. I'm testing with your ignition config now. The install seems to complete just fine, but after rebooting all I can see is "Probing EDD (edd=off to disable).... ok"

which is really annoying because I'd much rather see the regular start-up output and pin point what's happening. My guess is something is stuck w/ your ignition config. When I try a simpler config it works great. can you test your setup w/ this? http://pastebin.test.redhat.com/755230  (just drop-in your ssh key)

**Comment by zshi-redhat** [comment]
> I have a similar setup working w/ rhcos-410.8.20190415.2-metal-bios.raw and the only difference I can see is I'm using virtio instead of scsi devices. I'm testing with your ignition config now. The install seems to complete just fine, but after rebooting all I can see is "Probing EDD (edd=off to disable).... ok"

I didn't see the "Probing EDD" message, seems it can be disabled by setting ``edd=off`` in the kernel cmdline.

> 
> which is really annoying because I'd much rather see the regular start-up output and pin point what's happening. My guess is something is stuck w/ your ignition config. When I try a simpler config it works great. can you test your setup w/ this? http://pastebin.test.redhat.com/755230 (just drop-in your ssh key)

I tried with this ignition file, but it has the same result.
I can make sure that the image I used does have a partition labeled with 'boot', but it disappeared or perhaps not properly detected after rebooting:
```
[root@nfvpe-06 410.8.20190412.2]# guestfish -a  metal-bios.raw
><fs> run
><fs> list-filesystems
/dev/sda1: unknown
/dev/sda2: ext4
/dev/sda3: xfs
><fs> blkid /dev/sda2
DEVNAME: /dev/sda2
LABEL: boot
```

**Comment by mrguitar** [comment]
It's almost identical to what you posted:
sudo virt-install \
		--name $VM \
		--memory 2048 \
		--vcpus 4 \
		--disk bus=virtio,path=$VMIMAGE.qcow2 \
		--controller type=scsi,model=virtio-scsi \
		--network default \
		--pxe \
		--os-variant=rhel8.0

The only other thing I did differently was manually running gzip on the image file. It was ~4G downloaded and I compressed it before doing the install.

**Comment by jlebon** [comment]
> I just use the auto-generated ignition file which looks similar to yours, but it also includes a storage section; for example, here is the ignition file for bootstrap node: http://pastebin.test.redhat.com/755224

OK, just tried this same Ignition config locally on the latest RHCOS (though had to swap out all the `"**"` for `""` and added my SSH key), and it installed OK. Tried to reproduce your command-line as well:

```
$ virt-install --pxe --network network=default --name r8-pxe --memory 2000 --os-variant=rhel8.0 --disk size=8,bus=scsi,pool=default --nographics --boot menu=on,useserial=on --controller type=scsi,model=virtio-scsi
```

> The install seems to complete just fine, but after rebooting all I can see is "Probing EDD (edd=off to disable).... ok"

This is fixed by https://github.com/coreos/coreos-assembler/pull/473, which was backported, but I think we need a cosa rebuild.

If you wait long enough, it should eventually go to the login screen. Otherwise, you can also add `console=` args to the cmdline to see if it's hitting any errors. (If you didn't swap out the `**`, it's likely Ignition complaining).

>> can you test your setup w/ this? http://pastebin.test.redhat.com/755230 (just drop-in your ssh key)
>
> I tried with this ignition file, but it has the same result.

> ```
> # guestfish -a  metal-bios.raw
> ```

Hmm, so `metal-bios.raw` *is* uncompressed it looks like, right? Otherwise I don't think `guestfish` on it would've worked directly.

> the metal-bios.raw is downloaded via https://releases-redhat-coreos.cloud.paas.upshift.redhat.com/storage/releases/ootpa/410.8.20190412.2/rhcos-410.8.20190412.2-metal-bios.raw, it doesn't have gz suffix, but it's already in compressed format.

If you've copy/pasted the command directly from the release browser (which uses `-J --compressed`), `curl` will uncompress it for you. This is fixed in the latest release browser, which no longer recommends this. You can confirm whether your image is compressed with `file $FILE`.

**Comment by yuqi-zhang** [comment]
> This is fixed by coreos/coreos-assembler#473, which was backported, but I think we need a cosa rebuild.
That has been backported and built, just that we have having trouble with RHCOS builds, so hopefully you'll see new builds soon that has console.

> Hmm, so metal-bios.raw is uncompressed it looks like, right? 
Likely not, we actually stripped the `--compressed` from the release browser some time ago, and if you tried to use the unzipped image you will very likely not even install to disk correctly (as the size is much too large). I think zshi likely is just showing us the output after he did an unzip manually.

> If you didn't swap out the **, it's likely Ignition complaining
I have local builds with console output, let me see if I can wrangle something out of ignition

**Comment by yuqi-zhang** [comment]
Ok I can confirm that when I replace `"**"` with `""` gets the system to boot. I suspect ignition may be failing then. I added a `--nographics` to the `virt-install` command which gets me this:

```
[FAILED] Failed to start Ignition (disks).
See 'systemctl status ignition-disks.service' for details.
[DEPEND] Dependency failed for Initrd Default Target.
```
Which drops me to an emergency shell and:
```
# systemctl status ignition-disks.service
..
Apr 17 15:21:09 localhost ignition[681]: failed to fetch config: config is not >
Apr 17 15:21:09 localhost ignition[681]: failed to acquire config: config is no>
Apr 17 15:21:09 localhost ignition[681]: Ignition failed: config is not valid
```
I will PM you with details once I have a build with proper console.

**Comment by zshi-redhat** [comment]
> > I just use the auto-generated ignition file which looks similar to yours, but it also includes a storage section; for example, here is the ignition file for bootstrap node: http://pastebin.test.redhat.com/755224
> 
> OK, just tried this same Ignition config locally on the latest RHCOS (though had to swap out all the `"**"` for `""` and added my SSH key), and it installed OK. Tried to reproduce your command-line as well:
> 
> ```
> $ virt-install --pxe --network network=default --name r8-pxe --memory 2000 --os-variant=rhel8.0 --disk size=8,bus=scsi,pool=default --nographics --boot menu=on,useserial=on --controller type=scsi,model=virtio-scsi
> ```
> > The install seems to complete just fine, but after rebooting all I can see is "Probing EDD (edd=off to disable).... ok"
> 
> This is fixed by [coreos/coreos-assembler#473](https://github.com/coreos/coreos-assembler/pull/473), which was backported, but I think we need a cosa rebuild.
> 
> If you wait long enough, it should eventually go to the login screen. Otherwise, you can also add `console=` args to the cmdline to see if it's hitting any errors. (If you didn't swap out the `**`, it's likely Ignition complaining).
> 
> > > can you test your setup w/ this? http://pastebin.test.redhat.com/755230 (just drop-in your ssh key)
> > 
> > 
> > I tried with this ignition file, but it has the same result.
> 
> > ```
> > # guestfish -a  metal-bios.raw
> > ```
> 
> Hmm, so `metal-bios.raw` _is_ uncompressed it looks like, right? Otherwise I don't think `guestfish` on it would've worked directly.

I did the following steps before using guestfish:

```
mv metal-bios.raw metal-bios.raw.gz
gunzip metal-bios.raw.gz

```
The original metal-bios.raw file I downloaded is gzip compressed.
```
[root@nfvpe-06 410.8.20190412.2]# file rhcos-410.8.20190412.2-metal-bios.raw 
rhcos-410.8.20190412.2-metal-bios.raw: gzip compressed data, was "rhcos-410.8.20190412.2-metal-bios.raw", last modified: Fri Apr 12 16:42:20 2019, from Unix, original size -804257792
```

> 
> > the metal-bios.raw is downloaded via https://releases-redhat-coreos.cloud.paas.upshift.redhat.com/storage/releases/ootpa/410.8.20190412.2/rhcos-410.8.20190412.2-metal-bios.raw, it doesn't have gz suffix, but it's already in compressed format.
> 
> If you've copy/pasted the command directly from the release browser (which uses `-J --compressed`), `curl` will uncompress it for you. This is fixed in the latest release browser, which no longer recommends this. You can confirm whether your image is compressed with `file $FILE`.

**Comment by zshi-redhat** [comment]
> > I just use the auto-generated ignition file which looks similar to yours, but it also includes a storage section; for example, here is the ignition file for bootstrap node: http://pastebin.test.redhat.com/755224
> 
> OK, just tried this same Ignition config locally on the latest RHCOS (though had to swap out all the `"**"` for `""` and added my SSH key), and it installed OK. Tried to reproduce your command-line as well:
> 
> ```
> $ virt-install --pxe --network network=default --name r8-pxe --memory 2000 --os-variant=rhel8.0 --disk size=8,bus=scsi,pool=default --nographics --boot menu=on,useserial=on --controller type=scsi,model=virtio-scsi
> ```
> > The install seems to complete just fine, but after rebooting all I can see is "Probing EDD (edd=off to disable).... ok"
> 
> This is fixed by [coreos/coreos-assembler#473](https://github.com/coreos/coreos-assembler/pull/473), which was backported, but I think we need a cosa rebuild.
> 
> If you wait long enough, it should eventually go to the login screen. Otherwise, you can also add `console=` args to the cmdline to see if it's hitting any errors. (If you didn't swap out the `**`, it's likely Ignition complaining).
> 
> > > can you test your setup w/ this? http://pastebin.test.redhat.com/755230 (just drop-in your ssh key)
> > 
> > 
> > I tried with this ignition file, but it has the same result.
> 
> > ```
> > # guestfish -a  metal-bios.raw
> > ```
> 
> Hmm, so `metal-bios.raw` _is_ uncompressed it looks like, right? Otherwise I don't think `guestfish` on it would've worked directly.

I did the following steps before using guestfish:

```
mv metal-bios.raw metal-bios.raw.gz
gunzip metal-bios.raw.gz

```
The original metal-bios.raw file I downloaded is gzip compressed.
```
[root@nfvpe-06 410.8.20190412.2]# file rhcos-410.8.20190412.2-metal-bios.raw 
rhcos-410.8.20190412.2-metal-bios.raw: gzip compressed data, was "rhcos-410.8.20190412.2-metal-bios.raw", last modified: Fri Apr 12 16:42:20 2019, from Unix, original size -804257792
```

> 
> > the metal-bios.raw is downloaded via https://releases-redhat-coreos.cloud.paas.upshift.redhat.com/storage/releases/ootpa/410.8.20190412.2/rhcos-410.8.20190412.2-metal-bios.raw, it doesn't have gz suffix, but it's already in compressed format.
> 
> If you've copy/pasted the command directly from the release browser (which uses `-J --compressed`), `curl` will uncompress it for you. This is fixed in the latest release browser, which no longer recommends this. You can confirm whether your image is compressed with `file $FILE`.

**Comment by zshi-redhat** [comment]
> > > @zshi-redhat IIRC @yuqi-zhang hit the same issue and it was due to not having all the pxelinux files available. How are you setting up your PXE server? I personally do `dnf install -y syslinux-tftpboot` then grab all the files from `/tftpboot` (or you can `rpm2cpio`).
> > 
> > 
> > Thanks for the reply!
> > I did the same by installing syslinux-tftpboot package, copying pxelinux.0 and ldlinux.c32 to the tftpboot folder, it failed with the same error. Anything else I should try or any other configuration need to check?
> 
> The virt-install cmd I used for installing VMs is:
> 
> ```
> 	virt-install \
> 		--name ${NODE_NAMES[$index]} \
> 		--memory 2048 \
> 		--vcpus 4 \
> 		--disk size=8,bus=scsi,pool=default \
> 		--controller type=scsi,model=virtio-scsi \
> 		--network default \
> 		--mac=${MACS[$index]} \
> 		--pxe \
> 		--os-variant generic
> ```

Looks like there was a failure when using bus=scsi, not sure if it's relevant or critical enough to block the disk device system job:
```
Apr 18 02:28:03 localhost iscsid[602]: iSCSI daemon with pid=603 started!
Apr 18 02:28:03 localhost iscsid[602]: can't open InitiatorName configuration file /etc/iscsi/initiatorname.iscsi
Apr 18 02:28:03 localhost iscsid[602]: Warning: InitiatorName file /etc/iscsi/initiatorname.iscsi does not exist or does not contain a properly formatted InitiatorName. If using software iscsi (iscsi_tcp or ib_iser) or partial offload (bnx2i or cxgbi iscsi), you may not be able to log into or
```

I tried changing it to bus=virtio, but it didn't seem to work as it hangs in the first boot, didn't reach rebooting.
```
[  OK  ] Started Open-iSCSI.
[  OK  ] Started Create Volatile Files and Directories.
[  OK  ] Reached target System Initialization.
[  OK  ] Reached target Basic System.
         Starting dracut initqueue hook...
[  OK  ] Started dracut initqueue hook.
[  OK  ] Reached target Remote File Systems (Pre).
[  OK  ] Reached target CoreOS Installer Target.
[  OK  ] Started CoreOS Installer.
```

**Comment by zshi-redhat** [comment]
Update:  I tried new builds ``410.8.20190417.0`` per @yuqi-zhang  suggestion, the bootstrap VM booted successfully. I didn't change any ignition config nor the virt-install cmd, all the instructions used are the same with previous tests. One subtle difference is that the new build has suffix for metal-bios.raw.gz image naturally, I revised the pxelinux.cfg/default accordingly, but I don't think this was the reason of previous failure as I tried adding suffix before and previous builds can also boot after rebooting, it just failed due to the disk device problem mentioned in above comments.

**Comment by cjreyn** [comment]
For anyone else finding this thread, I had the same issue (hang at "Started CoreOS Installer") with the 4.1 Openshift images listed here: https://mirror.openshift.com/pub/openshift-v4/dependencies/rhcos/4.1/latest/ 

The pre-release version 4.2 seemed to solve this issue.
