### ISSUE TITLE
coreos-mount-var.service is not always stopped

### ISSUE THREAD

**Issue by jlebon** [coreos/ignition-dracut#70]
There's some kind of race going on where `coreos-mount-var.service` is not always stopped before switchroot, which means that we carry the `/var` bind mount into the real root, overriding any `/var` mount in fstab.

This seems to happen only when I have a large amount of filesystems defined (right now, `/var`, `/var/home`, `/var/lib`, and `/var/lib/containers`).

**Comment by ajeddeloh** [comment]
Reading https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Conflicts= indicates that we need some ordering directives. Specifically I think a `Before=initrd-switch-root.target` in https://github.com/coreos/ignition-dracut/blob/master/dracut/30ignition/ignition-complete.target might be right?

Do you have console logs for this?
