### ISSUE TITLE
The ignition-disks.service and ignition-files.service failed with lack of qemu_fw_cfg support on s390x qemu platform

### ISSUE THREAD

**Issue by zhengxiaomei123** [coreos/ignition-dracut#87]
Hi all, I tried to boot ignition on openstck s390x platform. 
The error is :
systemd[1]: Starting Ignition (disks)...
...skipping...
Jun 24 10:51:39 localhost ignition[666]: Ignition 0.31.0
Jun 24 10:51:39 localhost ignition[666]: reading system config file "/usr/lib/ignition/base.ign"
Jun 24 10:51:39 localhost ignition[666]: no config at "/usr/lib/ignition/base.ign"
Jun 24 10:51:39 localhost ignition[666]: parsed url from cmdline: ""
Jun 24 10:51:39 localhost ignition[666]: no config URL provided
Jun 24 10:51:39 localhost ignition[666]: reading system config file "/usr/lib/ignition/user.ign"
Jun 24 10:51:39 localhost ignition[666]: no config at "/usr/lib/ignition/user.ign"
Jun 24 10:51:39 localhost ignition[666]: op(1): [started]  loading QEMU firmware config module
Jun 24 10:51:39 localhost ignition[666]: op(1): executing: "modprobe" "qemu_fw_cfg"
Jun 24 10:51:39 localhost systemd[1]: Starting Open-iSCSI...
Jun 24 10:51:39 localhost systemd[1]: Started Ask OSTree to mount /var in initramfs.
Jun 24 10:51:39 localhost audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=ignition-ask-var-mount comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=>
Jun 24 10:51:39 localhost ignition[666]: op(1): [failed]   loading QEMU firmware config module: exit status 1: Cmd: "modprobe" "qemu_fw_cfg" Stdout: "" Stderr: "modprobe: FATAL: Module qemu_fw_cfg not found in directo>
Jun 24 10:51:39 localhost ignition[666]: failed to fetch config: exit status 1: Cmd: "modprobe" "qemu_fw_cfg" Stdout: "" Stderr: "modprobe: FATAL: Module qemu_fw_cfg not found in directory /lib/modules/5.0.9-200.fc29.>
Jun 24 10:51:39 localhost ignition[666]: failed to acquire config: exit status 1: Cmd: "modprobe" "qemu_fw_cfg" Stdout: "" Stderr: "modprobe: FATAL: Module qemu_fw_cfg not found in directory /lib/modules/5.0.9-200.fc2>
Jun 24 10:51:39 localhost ignition[666]: Ignition failed: exit status 1: Cmd: "modprobe" "qemu_fw_cfg" Stdout: "" Stderr: "modprobe: FATAL: Module qemu_fw_cfg not found in directory /lib/modules/5.0.9-200.fc29.s390x\n"
Jun 24 10:51:39 localhost systemd[1]: ignition-disks.service: Main process exited, code=exited, status=1/FAILURE
Jun 24 10:51:39 localhost systemd[1]: ignition-disks.service: Failed with result 'exit-code'.
Jun 24 10:51:39 localhost systemd[1]: Failed to start Ignition (disks).

qemu_fw_cfg is not supported on s390x, any config can be enabled to avoid this module? 

and besides, the other error in my environment is :
Ignition 0.31.0
Jun 25 02:34:22  ignition[1178]: reading system config file "/usr/lib/ignition/base.ign"
Jun 25 02:34:22  ignition[1178]: no config at "/usr/lib/ignition/base.ign"
Jun 25 02:34:22  ignition[1178]: no config URL provided
Jun 25 02:34:22  ignition[1178]: reading system config file "/usr/lib/ignition/user.ign"
Jun 25 02:34:22  ignition[1178]: no config at "/usr/lib/ignition/user.ign"
Jun 25 02:34:22  ignition[1178]: GET http://169.254.169.254/openstack/latest/user_data: attempt #1
Jun 25 02:34:22  ignition[1178]: GET result: OK
Jun 25 02:34:22  ignition[1178]: failed to fetch config: unsupported config version
Jun 25 02:34:22  ignition[1178]: failed to acquire config: unsupported config version
Jun 25 02:34:22  ignition[1178]: Ignition failed: unsupported config version

I tried the config version : 3.0.0 2.2.0 2.1.0 3.1.0 0.31.0, It all failed.

**Comment by ajeddeloh** [comment]
Does the config pass [`ignition-validate`](https://github.com/coreos/ignition/releases/tag/v0.32.0)?

**Comment by jlebon** [comment]
Hmm, interesting. So the platform ID seems correct, otherwise Ignition wouldn't have tried reaching out to the metadata server.

>  Jun 24 10:51:39 localhost ignition[666]: Ignition 0.31.0
>  Jun 25 02:34:22  ignition[1178]: failed to fetch config: unsupported config version

Is this based on RHEL or Fedora? Ignition in Fedora is at 2.0.0 and supports config version `3.0.0`. This Ignition version here should work with `2.2.0` though. Maybe Ignition somehow isn't fetching the right config? It should print out the config when it fails normally. Can you confirm that `"version": "2.2.0"` shows up there?

> qemu_fw_cfg is not supported on s390x, any config can be enabled to avoid this module?

Weird, Ignition shouldn't be trying to modprobe except on `qemu`. Can you share the kernel cmdline? How are you building this image?

**Comment by zhengxiaomei123** [comment]
> Does the config pass [`ignition-validate`](https://github.com/coreos/ignition/releases/tag/v0.32.0)?

Yes, It passed.

**Comment by zhengxiaomei123** [comment]
> Hmm, interesting. So the platform ID seems correct, otherwise Ignition wouldn't have tried reaching out to the metadata server.
> 
> > Jun 24 10:51:39 localhost ignition[666]: Ignition 0.31.0
> > Jun 25 02:34:22  ignition[1178]: failed to fetch config: unsupported config version
> 
> Is this based on RHEL or Fedora? Ignition in Fedora is at 2.0.0 and supports config version `3.0.0`. This Ignition version here should work with `2.2.0` though. Maybe Ignition somehow isn't fetching the right config? It should print out the config when it fails normally. Can you confirm that `"version": "2.2.0"` shows up there?
> 

Please confirm my understanding is right: It seems that the ignition version here(ignition 0.31.0) is an old version but it still can be supported on fedora with the config version is 2.2.0. 

I cannot get the print out config by ignition, maybe I don't open the debug mode of ignition. So I cannot config version 2.2.0 is here. How to do that? Thanks.

> > qemu_fw_cfg is not supported on s390x, any config can be enabled to avoid this module?
> 
> Weird, Ignition shouldn't be trying to modprobe except on `qemu`. Can you share the kernel cmdline? How are you building this image?

Yes, I found that my kernel cmdline is set the platform id to qemu, I changed it to openstack, this problem is solved.

**Comment by zhengxiaomei123** [comment]
@jlebon  Hi I got the config by the metadata url and the config is the right one that I uploaded when booting the instance.

Maybe the "unsupported config version" could be anything from a wrong cloud environment setup to something else mismatched in my image. each cloud platform has its own image format.

**Comment by zhengxiaomei123** [comment]
In my opinion, the issue should be open for the problem:
Ignition can not boot because of the lack of qemu_fw_cfg support on s390x qemu platform.

**Comment by tuan-hoang1** [comment]
Yeah that Ignition is super old, I stopped rebasing upstream since 02/2019. I'm going to rebuild again (and maybe trying enable/disable qemu_fw_cfg in those .service files). Last time I checked in other issues, qemu_fw_cfg won't affect s390x (also it seems going away soon?)

**Comment by jlebon** [comment]
>  Ignition can not boot because of the lack of qemu_fw_cfg support on s390x qemu platform.

We have a similar ticket for ppc64le already at least: https://github.com/coreos/ignition/issues/666. Would probably be better to either expand that ticket for s390x, or create a separate one? /cc @ajeddeloh

**Comment by ajeddeloh** [comment]
Yeah this should have its own Ignition issue. I don't know enough about s390x to suggest an alternative to `fw_cfg` but that's the right place to track it.

**Comment by zhengxiaomei123** [comment]
I will close the issue because the PR[https://github.com/coreos/ignition-dracut/pull/49] worked for it.
