### ISSUE TITLE
don't persist ifcfg for dhcp

### ISSUE THREAD

**Issue by cgwalters** [coreos/ignition-dracut#96]
BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1736875
Internal link: https://url.corp.redhat.com/a30c8df

Basically we only want to persist "manual" configuration; we shouldn't propagate the default `ip=dhcp` into the real root.

**Comment by darkmuggle** [comment]
@cgwalters I've assigned the bug to you.

**Comment by cgwalters** [comment]
PR in https://github.com/coreos/ignition-dracut/pull/98

**Comment by dustymabe** [comment]
closing this since #98 merged
